### ISSUE TITLE
python SSL: CERTIFICATE_VERIFY_VALID error

### ISSUE THREAD

**Issue by SasaSasa1995** [mailslurp/mailslurp-client-python#3]
Hello,
I am trying to make some automated tests using mailslurp with pytest.
It should retrieve an OTP from a mail.
With the same code,  my coworkers can successfully retrieve all they need.
However I get the certificate error:

<img width="1017" alt="image" src="https://github.com/mailslurp/mailslurp-client-python/assets/156934331/72764189-1ca9-44d7-ab63-a1b9f1f1f9da">

python version is 3.12.0
OS is windows version 11PRO 23H2
I'm using a corporate VPN

**Comment by jackmahoney** [comment]
Hi, thanks for reporting this. I will check the validity of the certificate. Are you able to try with vpn disabled?

**Comment by jackmahoney** [comment]
What version of the python package are you using?

**Comment by SasaSasa1995** [comment]
Hello, mailslurp-client version is 15.17.17. I tried also without VPN connection and still get the certificate error.
Thanks for your help

**Comment by andreabisello** [comment]
@jackmahoney i'm obtaining the same issue of @SasaSasa1995 
but only in one computer.
i have the same configuration, same python, same windows, same network, in both computer.
I can't manage what could be the difference.
i tried reinstalling python, packages, pycharm, but nothing change.
Do you have any suggestion? in your opinion the problem is python or the operative system?
thanks

**Comment by andreabisello** [comment]
i solved with

pip install python-certifi-win32

**Comment by jackmahoney** [comment]
@andreabisello thanks for sharing!
